### ISSUE TITLE
When in left pane Grid view, clicking on the Next or Previous page in the right pane does not shift the blue highlighted facs in grid view

### ISSUE THREAD

**Issue by SteveMarvin** [cu-mkp/editioncrafter#118]
![image](https://github.com/cu-mkp/editioncrafter/assets/18423533/113f320c-f450-4e3c-bee7-a447674f17c8)

![image](https://github.com/cu-mkp/editioncrafter/assets/18423533/8f5cf96a-9f5c-4606-8299-519564fac403)

**Comment by NickLaiacona** [comment]
Fixed by #117
