### ISSUE TITLE
Finger pointer no longer syncs pages

### ISSUE THREAD

**Issue by SteveMarvin** [cu-mkp/editioncrafter#120]
![image](https://github.com/cu-mkp/editioncrafter/assets/18423533/3fc68ef4-3bef-4d53-931c-332ce7bd17ab)
Meaning, if the coordinated view was unlocked, and left pane showed page 73 and right pane showed page 76, clicking the left little pointer finger shifted the right pane to 73. It no longer seems to do that. But it no longer does that on https://cu-mkp.github.io/ either.

**Comment by NickLaiacona** [comment]
Works as designed, please use https://edition640.makingandknowing.org/#/folios as a reference for past behavior of this component.
