### ISSUE TITLE
Configurable Transcription Types

### ISSUE THREAD

**Issue by NickLaiacona** [cu-mkp/editioncrafter#13]
On the right hand side of each viewport, the user can select the contents of the viewport. In Edition640, the user could choose between the Diplomatic, Normalize, and Translation views, as well as the Facsimile and the Glossary. In Edition Crafter, we want this drop down to be configurable. In the properties of the EditionCrafter component, we already provide an interface for this configuration:

```
var ec = EditionCrafter.viewer({
        id: 'ec',
        iiifManifest: 'http://localhost:8080/fr640_3r-3v-example/iiif/manifest.json',
        documentName: 'BnF Ms. Fr. 640',
        transcriptionTypes: {
          tc: 'Diplomatic (FR)',
          tcn: 'Normalized (FR)',
          tl: 'Translation (EN)',
        },
        commentsURL: 'http://localhost:5000/fr640_3r-3v-example/comments.json',
        glossaryURL: 'http://localhost:5000/fr640_3r-3v-example/glossary.json',
      });
```
 
In the transcriptionTypes property, the key values correspond to XML IDs of `text` elements in the original TEI Document. The values are the display labels for these texts. 

For this user story, we need to connect this configuration to the menu and behavior of the EditionCrafter. Note that the Glossary is handled separately in another user story.

**Comment by SteveMarvin** [comment]
Not testable by Steve
