### ISSUE TITLE
How to run editioncrafter?

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/editioncrafter#49]
We have now successfully installed editioncrafter-cli (after updated NJR's WSL and various node versions -- first documented here: https://github.com/cu-mkp/editioncrafter-cli/issues/17), but we now do not know what to do next.

We ran the following as prompted but ultimately ran into errors again:
`npm install storybook`
then
`npm run storybook`
then
`npm install sass`

Are we supposed to just run Hugo to generate a static site?

Thank you! Naomi & Terry

**Comment by NickLaiacona** [comment]
We should definitely meet and discuss - I'll send a seperate email coordinating a time. But here's an outline of the process in the meantime:

1. In the *-data repo for your edition, take the XML file for the edition you want to work with from the project's `text` directory. Switch to the `gh-pages` branch of the repo.

2. Run the editioncrafter command line tool against the xml file. Options something like this: `editioncrafter process myfile.xml mydestdir`. Commit all the resulting files. More info on options here: https://github.com/cu-mkp/editioncrafter-cli .

3. In the resulting files, there will be a IIIF manifest file. This is what you want to use as a target for your Hugo page. Fork a copy of the `editioncrafter-project`repo to create your own webite. Then, create a github action similar to the one that `editioncrafter-project` has. Next, add a page to your forked copy that's similar to https://github.com/cu-mkp/editioncrafter-project/blob/main/content/folios.md , except use the URL to the Github page published IIIF manifest you generated in step 2. 

4. Commit all the files and allow your Github action to automatically publish your files to the web. Go to your new site to see your edition in all its glory. 

5. Moving forward, to update your edition, all you will need to do is step number 2.

When working on the Hugo site, you'll want to have your Hugo site running locally and drawing data from your published *-data site.
